language: node_js

node_js:
  - 'stable'
  - 'lts/*'
  - '8'

env:
  - NODE_ENV=production

install:
  - NODE_ENV=dev npm install

jobs:
  include:
    - stage: Browser
      script: npm run test:browser
